<?xml version="1.0"?>
<robot xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#xacro" name="thymio">

  <xacro:include filename="$(find thymio_description)/urdf/wheel.urdf.xacro"/>
  <xacro:include filename="$(find thymio_description)/urdf/proximity_sensor.urdf.xacro"/>
  <xacro:include filename="$(find thymio_description)/urdf/imu.urdf.xacro"/>

  <xacro:arg name="left_wheel_mu" default="1.0"/>
  <xacro:arg name="right_wheel_mu" default="1.0"/>
  <xacro:property name="wheel_axis" value="0.0935"/>
  <xacro:property name="wheel_radius" value="0.022"/>
  <xacro:property name="wheel_torque" value="0.1"/>
  <xacro:arg name="wheel_kp" value="10000"/>
  <xacro:property name="body_mass" value="0.2"/>
  <xacro:arg name="body_kp" value="17500"/>
  <xacro:property name="wheel_mass" value="0.024"/>
  <xacro:arg name="proximity_max_range" default="0.12"/>
  <xacro:arg name="proximity_resolution" default="0.005"/>
  <xacro:arg name="proximity_fov" default="0.3"/>
  <xacro:arg name="name" default=""/>
  <xacro:arg name="publish_ground_truth" default="false"/>
  <xacro:arg name="ground_truth_frame_id" default="/world"/>
  <xacro:arg name="ground_truth_update_rate" default="10.0"/>
  <xacro:arg name="odom_max_rate" default="20.0"/>

  <xacro:macro name="thymio">
    <link name="base_link">
      <inertial>
        <origin xyz="0.0243 0 0.0205"/>
        <mass value="${body_mass}"/>
        <inertia ixx="${0.002199 * body_mass}" ixy="0" ixz="${-0.000760 * body_mass}" iyy="${0.002639 * body_mass}" iyz="0" izz="${0.002526 * body_mass}"/>
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://thymio_description/meshes/base_collision.dae"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.06 0 0.009"/>
        <geometry>
          <sphere radius="0.009"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://thymio_description/meshes/base_simple.dae"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="base_link">
      <selfCollide>false</selfCollide>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <kp>$(arg body_kp)</kp>
      <kd>1</kd>
    </gazebo>

    <xacro:wheel name="left" position="${wheel_axis * 0.5}" radius="${wheel_radius}" mass="${wheel_mass}" mu="$(arg left_wheel_mu)" kp="$(arg wheel_kp)"/>
    <xacro:wheel name="right" position="${-wheel_axis * 0.5}" radius="${wheel_radius}" mass="${wheel_mass}" mu="$(arg right_wheel_mu)" kp="$(arg wheel_kp)"/>

    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="center" xyz="0.08 0 0.035" rpy="0 0 0"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="center_left" xyz="0.0756 0.0261 0.035" rpy="0 0 0.33161"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="center_right" xyz="0.0756 -0.0261 0.035" rpy="0 0 -0.33161"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="left" xyz="0.063 0.0493 0.035" rpy="0 0 0.66323"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="right" xyz="0.063 -0.0493 0.035" rpy="0 0 -0.66323"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="rear_left" xyz="-0.03 0.0305 0.035" rpy="0 0 3.14159"/>
    <xacro:proximity_sensor group="proximity" range_max="$(arg proximity_max_range)" resolution="$(arg proximity_resolution)" fov="$(arg proximity_fov)" name="rear_right" xyz="-0.03 -0.0305 0.035" rpy="0 0 3.14159"/>
    <xacro:proximity_sensor group="ground" range_max="0.03" name="left" xyz="0.07157 0.01155 0.0009" rpy="0 1.5708 0.24311"/>
    <xacro:proximity_sensor group="ground" range_max="0.03" name="right" xyz="0.07157 -0.01155 0.0009" rpy="0 1.5708 -0.24311"/>

    <link name="laser_link"/>
    <joint name="base_laser_joint" type="fixed">
      <parent link="base_link"/>
      <child link="laser_link"/>
      <origin xyz="0 0 0.035"/>
    </joint>

    <xacro:imu ns="$(arg name)"/>

    <!-- see https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/src/gazebo_ros_diff_drive.cpp -->

    <gazebo>
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <legacyMode>false</legacyMode>
        <rosDebugLevel>Info</rosDebugLevel>
        <odometrySource>encoder</odometrySource>
        <alwaysOn>true</alwaysOn>
        <updateRate>$(arg odom_max_rate)</updateRate>
        <leftJoint>left_wheel_joint</leftJoint>
        <rightJoint>right_wheel_joint</rightJoint>
        <wheelSeparation>${wheel_axis}</wheelSeparation>
        <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
        <wheelTorque>${wheel_torque}</wheelTorque>
        <wheelAcceleration>0</wheelAcceleration>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <publishWheelJointState>true</publishWheelJointState>
        <publishWheelTF>false</publishWheelTF>
        <publishTf>true</publishTf>
        <robotBaseFrame>base_link</robotBaseFrame>
      </plugin>
    </gazebo>

    <!-- NOTE: The current version of the gazebo p3d plugin has a bug:
    the field child_frame_id is set to the name of the link (bodyName)
    and not to the frame name (frameName). -->


    <xacro:if value="$(arg publish_ground_truth)">
      <gazebo>
        <plugin name="ground_truth" filename="libgazebo_ros_p3d.so">
          <frameName>$(arg ground_truth_frame_id)</frameName>
          <bodyName>base_link</bodyName>
          <topicName>ground_truth/odom</topicName>
          <updateRate>$(arg ground_truth_update_rate)</updateRate>
        </plugin>
      </gazebo>
     </xacro:if>

  </xacro:macro>
</robot>
