<?xml version="1.0"?>
<package format="2">
  <name>asebaros</name>
  <version>0.2.0</version>
  <description>
    Bridge to access an Aseba network from ROS.
    For more information about Aseba, see: http://aseba.wikidot.com
  </description>

  <maintainer email="stephane@magnenat.net">Stéphane Magnenat</maintainer>
  <license>BSD</license>
  <url type="website">http://ros.org/wiki/asebaros</url>
  <url type="repository">https://github.com/ethz-asl/ros-aseba</url>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <depend>LibXml2</depend>
  <depend>asebaros_msgs</depend>
  <depend>diagnostic_updater</depend>
</package>
